### ISSUE TITLE
Make bridge being jigsaw

### ISSUE THREAD

**Issue by Ezoteric** [YUNG-GANG/YUNGs-Bridges#1]
Could you make it so that bridges are jigsaws so that it would also work for wider rivers.
I play with OTG as my generator and my river are wider.

Now with that said it should also be to not make river when the river is wider than * so it doesnt build bridges when river turn into lakes (but they are still called river) 

That would be much appreciated.

**Comment by yungnickyoung** [comment]
Not really feasible as structures don't have much terrain awareness
