### ISSUE TITLE
Bridges not spawning

### ISSUE THREAD

**Issue by Gamerbolts** [YUNG-GANG/YUNGs-Bridges#10]
Hi I am using your mod in my modpack and have been flying around for quite some time and have not seen any bridges. The default spawn freq was at 2 so I changed it. But still not getting anything and you can't use the /locate command because they are not there.

I am on Fabric 0.13.3
Minecraft 1.18.1
YungsBridges v1.0

Here is my config file. Any help is appreciated. Thank you!
[yungsbridges-fabric-1_18.zip](https://github.com/yungnickyoung/YUNGs-Bridges/files/8238356/yungsbridges-fabric-1_18.zip)

If you would like my latest file from my server this is it
[latest.log](https://github.com/yungnickyoung/YUNGs-Bridges/files/8238357/latest.log)

**Comment by Gamerbolts** [comment]
I updated the spawn freq. to 1000 for each bridge. we'll see how that works

**Comment by Gamerbolts** [comment]
Even at 1000 they are not spawning, or at least have not found any through my flying around

**Comment by yungnickyoung** [comment]
Lower number = more frequent. If you set it to 1000 the spawn rate will be exceptionally rare

**Comment by Gamerbolts** [comment]
ah I thought it was the other way around :D

**Comment by Gamerbolts** [comment]
They are spawning now. Sorry about that :)
