### ISSUE TITLE
Log spam setBlock in a far chunk

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [YUNG-GANG/YUNGs-Bridges#14]
I'm running a server with this mod and it spams me in the server console the message from the title
![image](https://user-images.githubusercontent.com/24871116/167232494-8c0c54b5-2c92-44c8-a42e-90fd69a2edce.png)
[latest.log](https://github.com/YUNG-GANG/YUNGs-Bridges/files/8644203/latest.log)

I'm using YUNG's Better Bridges in 1.18.2 with the latest YUNG's API version

**Comment by yungnickyoung** [comment]
Fixed in the first release for 1.19.

**Comment by RConTRS** [comment]
please fix it on 1.18.2 it's really annoying
