### ISSUE TITLE
Partially Generated Bridges

### ISSUE THREAD

**Issue by onemorelevel0** [YUNG-GANG/YUNGs-Bridges#2]
Hello, love the mod and I always look forward to your projects! I've been noticing around half of all generated bridges have been partially generated. I'm not sure if this is purposeful to give off an "old, ruined bridge" vibe, but I wanted to share it with you. There are also normal bridges spawning.

Here's my [mod list](https://docs.google.com/document/d/1rvFTW_3br3MAytz5fQGH8L4eewAbiehthgtIIwLjMFY/edit?usp=sharing). I do want to point out that these ruined bridges were occurring before having so many mods added. I haven't tested it out to see if any specific mod might be causing it, figured I would see if others were having similar problems before going through that work. I have some screenshots from a single seed, sorry about the potion effect:

![2021-10-25_01 03 01](https://user-images.githubusercontent.com/76502039/138659808-588f4175-57a9-4ef4-8a0e-5ed1d6a4ddb1.png)
![2021-10-25_01 03 21](https://user-images.githubusercontent.com/76502039/138659953-f7c63fff-ff90-4ed6-83b8-f982d1fde029.png)
![2021-10-25_01 03 47](https://user-images.githubusercontent.com/76502039/138659967-9dfd6c0f-595f-4853-bc35-a0186cb873ec.png)
![2021-10-25_01 04 10](https://user-images.githubusercontent.com/76502039/138659977-c4b3067a-41a7-461d-b626-96ef0c2efa2f.png)
![2021-10-25_01 04 40](https://user-images.githubusercontent.com/76502039/138659987-2952c1f8-6f63-479d-a02c-bc829d50b344.png)

**Comment by Ezoteric** [comment]
Dunno but maybe he made it so that there are also broken bridges :D
I mean having random stuff like that is nice :P

**Comment by yungnickyoung** [comment]
Ruined bridges are intended.
