### ISSUE TITLE
Logspam "detected setblock in far chunk"

### ISSUE THREAD

**Issue by Tempest-5ky** [YUNG-GANG/YUNGs-Bridges#22]
near-constant logspam of the following on a dedicated 1.18.2 server:
![image](https://user-images.githubusercontent.com/99220350/195221206-acb6f075-9e00-4b1e-b735-8e62bfc37b6f.png)

**Comment by Reshy** [comment]
https://pastebin.com/tfJvF51n

Similar issue.

**Comment by yungnickyoung** [comment]
Fixed in 1.19.x versions.
