### ISSUE TITLE
Where to edit spawn rate?

### ISSUE THREAD

**Issue by 119z** [YUNG-GANG/YUNGs-Bridges#25]
I use this mod in conjunction with Terralith and I wanted to edit the spawn rate as you suggest, but I don't see where? Neither this mod nor Terralith have any mod config, so I'm unsure of what I have to do.

I'm playing on 1.19.4 and using Fabric. Any help would be appreciated.

**Comment by LTVA1** [comment]
I have the same question, where I can edit it?
