### ISSUE TITLE
Forge version of the mod does not generate toml file

### ISSUE THREAD

**Issue by LTVA1** [YUNG-GANG/YUNGs-Bridges#26]
I installed 1.19.4 Forge version and I want to increase spawn rate, but for that I need the config file, however, no file is created in configs folder. Your other mods (better dungeons etc.) create the config files just fine, so there may be something wrong with this particular mod.

**Comment by yungnickyoung** [comment]
The bridge spawn rates must now be modified via data pack. The file you'll want to overwrite is this one: https://github.com/YUNG-GANG/YUNGs-Bridges/blob/multiloader/1.19.4/Common/src/main/resources/data/yungsbridges/worldgen/configured_feature/bridge_list.json

You can tweak the `chance` value for each bridge to change its spawn rate. Lower value = more common, higher value = more rare. I wouldn't touch any of the other variables.
