### ISSUE TITLE
Bridges generate broken/incomplete (Biomes o plenty)

### ISSUE THREAD

**Issue by danygarciagza** [YUNG-GANG/YUNGs-Bridges#28]
I thought it was intentional until i noticed every single bridge I have encountered generates like this, I'm not sure if it has something to do with BoP
<img width="655" alt="Screenshot 2024-02-08 at 9 16 41 p m" src="https://github.com/YUNG-GANG/YUNGs-Bridges/assets/159503437/8d7103ab-f747-43d0-bd8e-6d9b39cbd168">

**Comment by yungnickyoung** [comment]
It's intentional, some bridge types will always spawn broken
