### ISSUE TITLE
Bridges not accounting for frozen rivers

### ISSUE THREAD

**Issue by DemonSlayer112** [YUNG-GANG/YUNGs-Bridges#4]
![2021-10-31_16 09 48](https://user-images.githubusercontent.com/70122500/139604394-055fabe3-f7dc-448a-bae7-b8f1eb3af011.png)
Makes it difficult using boat.

**Comment by yungnickyoung** [comment]
What do you mean by not accounting for them?

**Comment by DemonSlayer112** [comment]
> What do you mean by not accounting for them?

Well, they spawn with no ice beneath them in frozen biomes.
Can use boat under them easily but in frozen biomes youll end up having to break the boat for every bridge you go under.
And to make sure ice wouldnt melt under a block i make tickspeed 1000 and placed ice under one and it never melted.

**Comment by yungnickyoung** [comment]
I believe the water not being frozen is vanilla behavior. Only water blocks exposed to air are turned to ice during world generation.

**Comment by XiFengXF** [comment]
What he means is that there is no need for bridges to generate in frozen rivers, otherwise it will be too obtrusive

**Comment by yungnickyoung** [comment]
I disagree, but if you don't like them you can blacklist frozen river biomes in the config.
