### ISSUE TITLE
Feature Suggestion: Support for Upstream

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [YUNG-GANG/YUNGs-Bridges#6]
Essentially what it says on the title. 
https://www.curseforge.com/minecraft/mc-mods/upstream This is the mod I'd love to see support for. The bridges would need to be much wider to make use of some of their river sizes though, its quite large.

**Comment by yungnickyoung** [comment]
Unfortunately it's not feasible to make bridges larger than the ones provided by this mod using my current method.
