### ISSUE TITLE
Suggestion: 1.18 and Fabric

### ISSUE THREAD

**Issue by theDerxu** [YUNG-GANG/YUNGs-Bridges#7]
As simple as it sounds, could you add 1.18 support and a fabric version? I know it's not very easy but It looks so good for RPG style playthroughs. :) (@yungnickyoung) (also [Issue#5](https://github.com/yungnickyoung/YUNGs-Bridges/issues/5) would be a great addon)

**Comment by theDerxu** [comment]
Is anyone able to respond? It's been a bit. I really want to play it with #5 and 1.18, and fabric, ik that's a lot but at least tell me if you can do it perhaps, thanks lol.

**Comment by yungnickyoung** [comment]
1.18 may happen eventually but is not currently being developed. #5 is currently not planned.

Btw this is meant for issue reports and cohesive feature suggestions, not questions. Please ask any questions on the Discord in the future!

**Comment by theDerxu** [comment]
Alright! Any way you could link the discord? I can't find it xd _(also if you have any news on if fabric is or isn't happening that would be nice, I would like to know if I should wait for an eventual update to play it with)_

**Comment by yungnickyoung** [comment]
http://discord.gg/rns3beq
